### ISSUE TITLE
Desktop - ChatSettingModal

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/FAITH#17]
[Desktop - ChatSettingModal](https://www.figma.com/design/Ff2YeRL2BEG24idF2CUNKc/Faith?node-id=1-4&m=dev)
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/8a431b6b-39c9-479e-bc46-6de5b92afb31)

**Comment by Julian0701** [comment]
- take 7 hrs, done
