### ISSUE TITLE
Desktop - TopicModal

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/FAITH#18]
[Desktop - TopicModal
](https://www.figma.com/design/Ff2YeRL2BEG24idF2CUNKc/Faith?node-id=1-4&m=dev)
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/d59ec8f8-2b98-4525-bc2a-617b35fecb07)

**Comment by Julian0701** [comment]
- take 5 hrs, done
