### ISSUE TITLE
Desktop - TopicItem

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/FAITH#19]
[Desktop - TopicItem](https://www.figma.com/design/Ff2YeRL2BEG24idF2CUNKc/Faith?node-id=1-4&m=dev)
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/db57f32c-a9f9-4ca5-a273-2f4f78278d92)

**Comment by Julian0701** [comment]
- take 1.5 hrs
