### ISSUE TITLE
[Plan] iSunChat front-end development based on mockup

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/FAITH#43]
- [x] CAFECA-IO/iSunFA#1237
- [x] 根據現有的 mockup 去規劃桌面版跟行動版的前端開發
- ref: [mockup](https://www.figma.com/design/Ff2YeRL2BEG24idF2CUNKc/iSunChat?node-id=1-4&m=dev)｜

**Comment by Julian0701** [comment]
預估共 18 點

  | Desktop | Points
-- | -- | --
UserCodeModal  | #55  | 3
FeedbackModal  | #56 | 1
FolderOverviewPage  | #57 | 3
ChatList  | #58 | 3
UpdateLinkModal  | #59 | 3
MoveChatModal  | #60 | 2
shared links management  | #61 | 3

**Comment by Julian0701** [comment]
手機版共 45 點

  | Mobile | Points
-- | -- | --
NavBar  | #62  | 3
ChatSidebar  | #63 | 2
SettingModal  | #64 | 8
SubscriptionPage  | #65 | 5
TopicBrowsePage  | #66 | 2
TopicSection  | #67 | 5
TopicModal | #68 | 2
ReportModal | #69 | 1
FolderOverviewPage | #70 | 3
ChatList | #71 | 3
MoveChatModal | #72 | 1
UpdateLinkModal | #73 | 1
FeedbackModal | #74 | 1
ChatThreadSection | #75 | 5
LoginPage | #76 | 2
UserCodeModal | #77 | 1

**Comment by Julian0701** [comment]
- take 5 hrs, done
- 共新增 63 pt
